name: CI

on:
  push:
    branches:
      - master
      - 'v[0-9]*'
    tags:
      - 'v[0-9]*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
        django_version: ["32", "42", "50"]
        exclude:
          - django_version: "32"
            python_version: "3.11"
          - django_version: "32"
            python_version: "3.12"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Choose Python version ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python_version }}'
          cache: 'pip'
      - name: install tox (with uv)
        run: python3 -m pip install tox tox-uv
      - name: run tox
        run: tox -e 'py${{ matrix.python_version }}-django${{ matrix.django_version }}'
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: sk1p/django-codemirror2 

  release:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install tooling
        run: pip install build
      - name: Build wheel and sdist
        run: python -m build --wheel --sdist && unzip -l dist/*.whl
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
